name: sunspot cron

on:
  schedule:
    - cron: '35 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout hpc-h5
      uses: actions/checkout@v3    
    - name: cURL request
      run: curl -s -o out.json 'https://my.cdash.org/api/v1/index.php?project=HDF5'
    - id: date
      run: echo "##[set-output name=data;]$(python ./bin/cdash.py uan-0001)"

    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: out.json
        path: ${{ runner.workspace }}/out.json
      
    - name: Time badge
      uses: RubbaBoy/BYOB@v1.3.0
      with:
        NAME: Sunspot
        LABEL: 'Sunspot Test Failures'
        STATUS: ${{ steps.date.outputs.data }}
        COLOR: 00EEFF
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        REPOSITORY: hyoklee/hpc-h5
        ACTOR: hyoklee
